name: lando-compose
services:
  pghero2:
    type: compose
    app_mount: false
    moreHttpPorts:
      - "8080"
    services:
      image: ankane/pghero
      command: puma -C config/puma.rb
      environment:
        DATABASE_URL: postgres://postgres:password@custom-database2:5432/test
      ports:
        - "8080"
  pghero:
    type: compose
    app_mount: disabled
    moreHttpPorts:
      - "8080"
    services:
      image: ankane/pghero
      command: puma -C config/puma.rb
      environment:
        DATABASE_URL: postgres://postgres:password@custom-database:5432/test
      ports:
        - "8080"
  custom-service:
    type: compose
    services:
      image: drupal:8
      command: docker-php-entrypoint apache2-foreground
      ports:
        - "80"
    volumes:
      my-volume:
    networks:
      my-network:
  custom-service2:
    type: compose
    services:
      image: pirog/custom:hyperion
      build: ./custom
      networks:
        - my-network
      volumes:
        - ./chaosmonkey.txt:/tmp/monkeysee.txt
      command: tail -f /dev/null
  custom-database:
    type: compose
    services:
      image: postgres:9.4
      command: docker-entrypoint.sh postgres
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
      volumes:
        - data_volume:/var/lib/postgresql/data
    volumes:
      data_volume:
  custom-database2:
    type: compose
    services:
      image: pirog/postgres:9.4
      build:
        context: ./custom
        dockerfile: Dockerfile-database
      command: docker-entrypoint.sh postgres
      environment:
        POSTGRES_PASSWORD: password
        POSTGRES_DB: test
